##include endian_27aq18pth4y0m1zzesylkwjk5.mk
#
# A POSIX Makefile snippet for auto-generating endianness header file.

# This macro defines all files possibly generated by the rules of this
# snippet. Use it in your "clean" target to remove those files.
ENDIAN_27AQ18PTH4Y0M1ZZESYLKWJK5_GENERATED = \
	endian_27aq18pth4y0m1zzesylkwjk5.h test_endianness

# List of additional files required by this snippets in order to work
# correctly. Be sure to include them with your other project files when
# distributing the source code of your project.
ENDIAN_27AQ18PTH4Y0M1ZZESYLKWJK5_PREREQUISITES = \
	endian_27aq18pth4y0m1zzesylkwjk5.h.in test_endianness.c

# This is "C" header file which will be generated.
endian_27aq18pth4y0m1zzesylkwjk5.h: \
	endian_27aq18pth4y0m1zzesylkwjk5.h.in test_endianness
	@delta=0; e=`./test_endianness | tr -- - " "` && set -- $$e \
	&& while test $$# -ge 2; \
	do \
		ndelta=`expr $$1 - $$2`; \
		if test $$delta = 0; \
		then \
			test $$ndelta = 0 && break; \
			delta=$$ndelta; \
		elif test $$delta != $$ndelta; \
		then \
			delta=0; break; \
		fi; \
		shift; \
	done; \
	case $$delta in \
		-1) endian=LITTLE;; \
		1) endian=BIG;; \
		*) endian=UNSUPPORTED; \
	esac; \
	notice1="Automatically generated on `LC_TIME=C date`."; \
	notice2="DO NOT EDIT!"; \
	sed -e "s/{END}/$$endian/" \
		-e "s/{NOTICE1}/$$notice1/; s/{NOTICE2}/$$notice2/" \
		$@.in > $@
